### ISSUE TITLE
Date for 'locality/current_ballot' endpoint returns null

### ISSUE THREAD

**Issue by jnmarcus** [caciviclab/disclosure-backend#262] opened 2016-08-14 21:38 UTC

**Comment by mikeubell** [comment] 2016-08-24 21:07
@KyleW Seems like this is related to #238.

**Comment by adborden** [comment] 2016-08-25 02:32
This is just data missing. We parse some of the ballot data from Netfile, but we've agreed that most of the ballot data will be manually entered, so I just entered it http://api.caciviclab.org/admin/ballot/ballot/ 

@tdooner this is going to be a problem if we are regularly resetting the DB. No one has access to the django admin anymore to see what I'm talking about.

**Comment by tdooner** [comment] 2016-08-26 03:16
Okay - I won't reset the database until we can get an automated system in place for importing this data. What data exactly did you enter? Was it stuff that `manage.py importoaklandcandidates` imports?

**Comment by adborden** [comment] 2016-08-26 05:11
On Thu, 2016-08-25 at 20:16 -0700, Tom Dooner notifications@github.com wrote:

> Okay - I won't reset the database until we can get an automated system in place for importing this data. What data exactly did you enter? Was it stuff that `manage.py importoaklandcandidates` imports?

Oh good call. Change this to 2016-11-08, and we've got it :)

https://github.com/caciviclab/disclosure-backend/blob/bug/current-ballot/finance/management/commands/importoaklandcandidates.py#L38

## 

Aaron D Borden
Human and Hacker

**Comment by adborden** [comment] 2016-09-17 19:04
I'm going to call this fixed, the import script _does_ set an election date now. We're moving to the [static api](https://github.com/caciviclab/disclosure-backend-static) anyway, so the issue isn't relevant. Feel free to comment.

**Closed as completed by adborden** 2016-09-17 19:04 UTC
