### ISSUE TITLE
KeyError 'filingStartDate'

### ISSUE THREAD

**Issue by adborden** [caciviclab/disclosure-backend#247] opened 2016-06-02 04:23 UTC
The title isn't quite correct, I lost the stack trace, but have seen this KeyError pop up. Looks like Netfile has changed some fields and added some new ones. Here's a diff of the column headers between old and new csvs, sorted.

```
--- data/netfile/csv/netfile_2015_CMA_cal201_export.csv.txt 2016-06-01 21:11:12.002740733 -0700
+++ data/netfile/csv/netfile_2015_CMA_cal201_export.new.csv.txt 2016-06-01 21:11:12.005740798 -0700
@@ -18,9 +18,12 @@
 end_Bal
 entity_Cd
 externalId
-filerId
+filerLocalId
 filerName
+filerStateId
+filingEndDate
 filingId
+filingStartDate
 form_Type
 g_From_E_F
 int_CmteId
```

**Comment by tdooner** [comment] 2016-06-09 22:40
The stacktrace is actually what is breaking our import process in production:

http://admin.caciviclab.org/

```
Report for module 'xformnetfile'

Date:
  June 9, 2016, 2:08 a.m.

Command:
  ['python', '/data/backend/current/manage.py', 'xformnetfilerawdata', '--no-color', '--skip-download', '--verbosity=3']

Return code:
  1

Stdout (if any):

Found 67 agencies
[36;1mLoading disclosure data into database.[0m
[36;1mThere are 718744 rows in /data/backend/1455079647/disclosure/../data/netfile/csv/netfile_cal201_transaction.csv[0m
Loading 500301 rows of Form 460 Sched. A data.


Stderr (if any):

Traceback (most recent call last):
  File "/data/backend/current/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/data/backend/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/data/backend/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/data/backend/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/data/backend/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/data/backend/1455079647/netfile_raw/management/commands/downloadnetfilerawdata.py", line 172, in handle
    self.load()
  File "/data/backend/1455079647/finance/management/commands/xformnetfilerawdata.py", line 369, in load
    agency_fn=lambda row: self.get_agency(
  File "/data/backend/1455079647/finance/management/commands/xformnetfilerawdata.py", line 324, in load_f460A_data
    agency = agency_fn(minimal_row)
  File "/data/backend/1455079647/finance/management/commands/xformnetfilerawdata.py", line 370, in <lambda>
    row['filerId'].split('-')[0]))
  File "/data/backend/env/local/lib/python2.7/site-packages/pandas/core/series.py", line 557, in __getitem__
    result = self.index.get_value(self, key)
  File "/data/backend/env/local/lib/python2.7/site-packages/pandas/core/index.py", line 1804, in get_value
    raise e1
KeyError: 'filerId'
```

**Comment by KyleW** [comment] 2016-07-13 03:55
@monkeyHippies has offered to help with this. Seems like there's 2 tracts of work. The first is make the script run as is. The second is to potentially rethink the deduping strategy.

I'd suggest making the scripts work as is first while we discuss the longer term approach.

**Comment by monkeyhippies** [comment] 2016-07-14 02:45
Looking at @tdooner 's stack trace, the file `finance/management/commands/xformnetfilerawdata.py` seems to be different in production and master branch... Specifically, I can't find `row['filerId'].split('-')[0]` anywhere in master branch. Also, `agency_fn=lambda row: self.get_agency(` isn't found in line 369.

I'm new to django, so maybe I'm missing something?

I'm also having trouble reproducing the error locally.

**Comment by KyleW** [comment] 2016-07-14 02:59
I've seen this error recently,  but I'm not near home box to verify. Check the develop branch?

I believe develop may be pretty far ahead of master.

**Comment by mikeubell** [comment] 2016-08-24 21:04
I believe this was fixed in my and/or Tom's commit last week.

**Closed as completed by mikeubell** 2016-08-24 21:04 UTC
Labels: MVP
