### ISSUE TITLE
downloadzipcodedata fails

### ISSUE THREAD

**Issue by rkiddy** [caciviclab/disclosure-backend#40] opened 2015-10-01 00:06 UTC
I will see if I can see what is wrong, but I thought I was following the directions. I did a 'git pull' and then this:

```
 (env)ray@ubu01:~/Projects/OpenCA/disclosure-backend$ mysql 
 Welcome to the MySQL monitor.  Commands end with ; or \g.
 Your MySQL connection id is 86
 Server version: 5.6.19-0ubuntu0.14.04.1 (Ubuntu)

 Copyright (c) 2000, 2014, Oracle and/or its affiliates. All rights reserved.

 Oracle is a registered trademark of Oracle Corporation and/or its
 affiliates. Other names may be trademarks of their respective
 owners.

 Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

 mysql> 
 mysql> 
 mysql> drop database calaccess_raw;
 Query OK, 109 rows affected (5.26 sec)

 mysql> create database calaccess_raw;
 Query OK, 1 row affected (0.00 sec)

 mysql> quit
 Bye
 (env)ray@ubu01:~/Projects/OpenCA/disclosure-backend$ 
 (env)ray@ubu01:~/Projects/OpenCA/disclosure-backend$ python disclosure-backend/manage.py migrate
 Operations to perform:
   Synchronize unmigrated apps: staticfiles, calaccess_raw, netfile, messages, zipcode_metro
   Apply all migrations: admin, contenttypes, auth, sessions
 Synchronizing apps without migrations:
   Creating tables...
     Creating table CVR_SO_CD
     Creating table CVR2_SO_CD
     Creating table CVR_CAMPAIGN_DISCLOSURE_CD
     Creating table CVR2_CAMPAIGN_DISCLOSURE_CD
     Creating table RCPT_CD
     Creating table CVR3_VERIFICATION_INFO_CD
     Creating table LOAN_CD
     Creating table S401_CD
     Creating table EXPN_CD
     Creating table F495P2_CD
     Creating table DEBT_CD
     Creating table S496_CD
     Creating table SPLT_CD
     Creating table S497_CD
     Creating table F501_502_CD
     Creating table S498_CD
     Creating table CVR_REGISTRATION_CD
     Creating table CVR2_REGISTRATION_CD
     Creating table CVR_LOBBY_DISCLOSURE_CD
     Creating table CVR2_LOBBY_DISCLOSURE_CD
     Creating table LOBBY_AMENDMENTS_CD
     Creating table F690P2_CD
     Creating table LATT_CD
     Creating table LEXP_CD
     Creating table LCCM_CD
     Creating table LOTH_CD
     Creating table LEMP_CD
     Creating table LPAY_CD
     Creating table FILERNAME_CD
     Creating table FILER_FILINGS_CD
     Creating table FILINGS_CD
     Creating table SMRY_CD
     Creating table CVR_E530_CD
     Creating table TEXT_MEMO_CD
     Creating table ACRONYMS_CD
     Creating table ADDRESS_CD
     Creating table BALLOT_MEASURES_CD
     Creating table EFS_FILING_LOG_CD
     Creating table FILERS_CD
     Creating table FILER_ACRONYMS_CD
     Creating table FILER_ADDRESS_CD
     Creating table FILER_ETHICS_CLASS_CD
     Creating table FILER_INTERESTS_CD
     Creating table FILER_LINKS_CD
     Creating table FILER_STATUS_TYPES_CD
     Creating table FILER_TO_FILER_TYPE_CD
     Creating table FILER_TYPES_CD
     Creating table FILER_XREF_CD
     Creating table FILING_PERIOD_CD
     Creating table GROUP_TYPES_CD
     Creating table HEADER_CD
     Creating table HDR_CD
     Creating table IMAGE_LINKS_CD
     Creating table LEGISLATIVE_SESSIONS_CD
     Creating table LOBBYING_CHG_LOG_CD
     Creating table LOBBYIST_CONTRIBUTIONS1_CD
     Creating table LOBBYIST_CONTRIBUTIONS2_CD
     Creating table LOBBYIST_CONTRIBUTIONS3_CD
     Creating table LOBBYIST_EMPLOYER1_CD
     Creating table LOBBYIST_EMPLOYER2_CD
     Creating table LOBBYIST_EMPLOYER3_CD
     Creating table LOBBYIST_EMPLOYER_FIRMS1_CD
     Creating table LOBBYIST_EMPLOYER_FIRMS2_CD
     Creating table LOBBYIST_EMP_LOBBYIST1_CD
     Creating table LOBBYIST_EMP_LOBBYIST2_CD
     Creating table LOBBYIST_FIRM1_CD
     Creating table LOBBYIST_FIRM2_CD
     Creating table LOBBYIST_FIRM3_CD
     Creating table LOBBYIST_FIRM_EMPLOYER1_CD
     Creating table LOBBYIST_FIRM_EMPLOYER2_CD
     Creating table LOBBYIST_FIRM_LOBBYIST1_CD
     Creating table LOBBYIST_FIRM_LOBBYIST2_CD
     Creating table LOOKUP_CODES_CD
     Creating table NAMES_CD
     Creating table RECEIVED_FILINGS_CD
     Creating table REPORTS_CD
     Creating table netfile_agency
     Creating table netfile_cal201_transaction
     Creating table ZIPCODE_METRO
     Running deferred SQL...
   Installing custom SQL...
 Running migrations:
   Rendering model states... DONE
   Applying contenttypes.0001_initial... OK
   Applying auth.0001_initial... OK
   Applying admin.0001_initial... OK
   Applying contenttypes.0002_remove_content_type_name... OK
   Applying auth.0002_alter_permission_name_max_length... OK
   Applying auth.0003_alter_user_email_max_length... OK
   Applying auth.0004_alter_user_username_opts... OK
   Applying auth.0005_alter_user_last_login_null... OK
   Applying auth.0006_require_contenttypes_0002... OK
   Applying sessions.0001_initial... OK
 (env)ray@ubu01:~/Projects/OpenCA/disclosure-backend$  
 (env)ray@ubu01:~/Projects/OpenCA/disclosure-backend$ python disclosure-backend/manage.py downloadcalaccessrawdata --use-test-data
 Using test data
 Cleaning data files
 [################################] 80/80 - 00:00:02
 Loading data files
 [################################] 76/76 - 00:00:46
 Done!
 (env)ray@ubu01:~/Projects/OpenCA/disclosure-backend$ 
 (env)ray@ubu01:~/Projects/OpenCA/disclosure-backend$ python disclosure-backend/manage.py downloadzipcodedata
 Downloading/unzipping raw data files
 ok.
 Loading CSV files
 Traceback (most recent call last):
   File "disclosure-backend/manage.py", line 9, in <module>
     execute_from_command_line(sys.argv)
   File "/home/ray/Projects/OpenCA/disclosure-backend/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
     utility.execute()
   File "/home/ray/Projects/OpenCA/disclosure-backend/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
     self.fetch_command(subcommand).run_from_argv(self.argv)
   File "/home/ray/Projects/OpenCA/disclosure-backend/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 393, in run_from_argv
     self.execute(*args, **cmd_options)
   File "/home/ray/Projects/OpenCA/disclosure-backend/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
     output = self.handle(*args, **options)
   File "zipcode_metro/management/commands/downloadzipcodedata.py", line 49, in handle
     self.load()
   File "zipcode_metro/management/commands/downloadzipcodedata.py", line 73, in load
     super(Command, self).load('zipcode_metro.ZipCodeMetro')
   File "/home/ray/Projects/OpenCA/disclosure-backend/env/src/django-calaccess-raw-data/calaccess_raw/management/commands/loadcalaccessrawfile.py", line 33, in load
     model = get_model("calaccess_raw", model_name)
   File "/home/ray/Projects/OpenCA/disclosure-backend/env/local/lib/python2.7/site-packages/django/apps/registry.py", line 202, in get_model
     return self.get_app_config(app_label).get_model(model_name.lower())
   File "/home/ray/Projects/OpenCA/disclosure-backend/env/local/lib/python2.7/site-packages/django/apps/config.py", line 162, in get_model
     "App '%s' doesn't have a '%s' model." % (self.label, model_name))
 LookupError: App 'calaccess_raw' doesn't have a 'zipcode_metro.zipcodemetro' model.
 (env)ray@ubu01:~/Projects/OpenCA/disclosure-backend$ 
```

**Comment by adborden** [comment] 2015-10-01 02:41
Great report, @rkiddy. This is a dupe of #30 and is left-over from our calaccess_raw cleanup. #39 fixes the issue, so if you're feeling adventurous, you can switch to bug/30 branch, `pip install -r requirements.txt` to pull in the forked calaccess dependency and go from there.

**Closed as completed by adborden** 2015-10-01 02:41 UTC

**Comment by rkiddy** [comment] 2015-10-02 22:17
@adborden, I cannot tell if you are being facetious or not. :-) I will try to keep up with you all. It is working if I pull bug/30. Thanx.

**Comment by adborden** [comment] 2015-10-03 22:39
@rkiddy no, not being facetious, sorry if I sounded that way. Every report is a positive contribution, even if it's about an existing issue. It says to me that more folks are running into the issue and we should prioritize the fix.

I'm glad it's working for you, and I'll merge it in now that I know at least someone else looked at it. Thanks!
